name: artifacts and outputs
on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/*"
  workflow_dispatch:
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v6
  test:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - name: get-code
        uses: actions/checkout@v6
      - name: cache dependencies
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/pachage-lock.json') }}
      - name: install dependencies
        run: npm ci
      - name: test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps: 
      - name: get-code
        uses: actions/checkout@v6
      - name: install dependencies
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies code
        run: npm ci
      - name: build code
        run: npm run build
      - name: publish script file
        id: publish
        run: find dist/assets/*.js -type f -execdir echo "script-file={} >> $GITHUB_OUTPUT" ";"
      - name: upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v6
        with:
          name: dist-files
      - name: list artifact files
        run: ls
      - name: display job outputs
        run: echo "${{ needs.build.outputs.script-file }}"
      - name: deploy code
        run: echo "code deployed"


