name: artifacts and outputs
on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/*"
  workflow_dispatch:
jobs:
  Get-context:
    runs-on: ubuntu-latest
    steps:
      - name: display context
        run: echo "${{ toJSON(github) }}"
  Get-code:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v6
  Install-dep:
    needs: Get-code
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v6
      - name: install dependencies for node app
        run: npm ci
  lint-code:
    needs: Install-dep
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v6
      - name: install dependencies for node app
        run: npm ci
      - name: lint code for syntax correction
        run: npm run lint
  test-code:
    needs: lint-code
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v6
      - name: install dependencies for node app
        run: npm ci
      - name: perform tests on code
        run: npm run test
  build-code:
    needs: test-code
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v6
      - name: install dependencies for node app
        run: npm ci
      - name: build code
        run: npm run build
      - name: upload artifacts
        uses: actions/upload-artifact@v6
        with:
          path: dist
          name: dist-files        
  deploy:
    needs: build-code
    runs-on: ubuntu-latest
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v6
        with:
          name: dist-files
      - name: get ip address
        run: ipaddr
      - name: deploy code
        run: echo "fake deployment"



